apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30560
  selector:
    app: kibana
  type: NodePort