apiVersion: v1
kind: Service
metadata:
  name: quesma-ext-admin
{{/*  labels:*/}}
{{/*    {{- include "quesma.labels" . | nindent 4 }}*/}}
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30999
  selector:
    {{- include "quesma.selectorLabels" . | nindent 4 }}
