apiVersion: v1
kind: Service
metadata:
  name: quesma-ext-frontend
{{/*  labels:*/}}
{{/*    {{- include "quesma.labels" . | nindent 4 }}*/}}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30808
  selector:
    {{- include "quesma.selectorLabels" . | nindent 4 }}
