version: 2
updates:
  - package-ecosystem: gomod
    directory: /quesma
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
