installationId: "just-Quesma-smoke-test-instance"
frontendConnectors:
  - name: elasticsearchFakedAPI
    type: elasticsearch-fe
    config:
      listenPort: 8080
backendConnectors:
  - name: my-minimal-elasticsearch
    type: elasticsearch
    config:
      url: "http://elasticsearch:9200"
  - name: my-clickhouse-cloud-data-source
    type: clickhouse-os
    config:
      url: "clickhouse://clickhouse:9000"
processors:
  - name: elasticsearch-to-clickhouse-processor
    type: quesma-v1-processor
    config:
      mode: "dual-write-query-clickhouse"
      enableElasticsearchIngest: true
      indexes:
        kibana_sample_data_ecommerce:
        kibana_sample_data_flights:
        kibana_sample_data_logs:
        logs-generic-default:
          schemaOverrides:
            fields:
              "message":
                type: text
        windows_logs:   # Used for EQL e2e tests
