version: "3.7"
services:
  quesma:
    build: quesma
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - mitmproxy
      - clickhouse
    links:
      - elasticsearch
    restart: unless-stopped
  log-generator:
    build: log-generator
    depends_on:
      - mitmproxy
    links:
      - "mitmproxy"
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    links:
      - "mitmproxy"
    environment:
      ELASTICSEARCH_HOSTS: '["http://mitmproxy:8080"]'
    depends_on:
      - elasticsearch
      - mitmproxy
    ports:
      - "5601:5601"
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
  mitmproxy:
    image: mitmproxy/mitmproxy:10.1.5
    tty: true
    ports:
      - "9200:8080"
      - "8081:8081"
    command: mitmweb --no-web-open-browser --web-host 0.0.0.0 --mode reverse:http://quesma:8080/ -s /var/mitmproxy/request.py
    restart: unless-stopped
    volumes:
      - ./mitmproxy:/var/mitmproxy
