# TEST CONFIGURATION
mode: "dual-write-query-clickhouse"
licenseKey: "cdd749a3-e777-11ee-bcf8-0242ac150004"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
connectors:
  my-clickhouse-connector:
    type: "clickhouse"
clickhouse:
  url: "clickhouse://localhost:9000"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  remoteUrl: "https://api.quesma.com/phone-home"
  path: "logs"
  level: "info"
indexes:
  example-index:
  kibana_sample_data_ecommerce:
  kibana_sample_data_flights:
  kibana_sample_data_logs:
    schemaOverrides:
      fields:
        timestamp:
          type: alias
          targetColumnName: "@timestamp"
  kafka-example-topic:
  logs-generic-default:
    fullTextFields: ["message", "host.name"]
  device-logs:
    fullTextFields: ["message"]
  phone_home_logs:
    fullTextFields: ["message"]
  windows_logs:
  phone_home_data:
    fullTextFields: ["message"]


