# TEST CONFIGURATION
mode: "dual-write-query-clickhouse"
licenseKey: "cdd749a3-e777-11ee-bcf8-0242ac150004"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
clickhouse:
  url: "clickhouse://localhost:9000"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  remoteUrl: "https://api.quesma.com/phone-home"
  path: "logs"
  level: "info"
indexes:
  - pattern: "example*"
    enabled: true
  - pattern: "kibana_sample_data_ecommerce"
    enabled: true
  - pattern: "kibana_sample_data_flights"
    enabled: true
  - pattern: "kibana_sample_data_logs"
    enabled: true
    aliases:
      timestamp:
        targetfieldname: "timestamp"
        sourcefieldname: "@timestamp"
  - pattern: "kafka-example-topi*"
    enabled: true
  - pattern: "logs-generic-*"
    enabled: true
    fullTextFields: ["message", "host.name"]
  - pattern: "device*"
    enabled: true
    fullTextFields: ["message"]
  - pattern: "phone_home_logs"
    enabled: true
    fullTextFields: ["message"]
  - pattern: "windows_logs"
    enabled: true
  - pattern: "phone_home_data"
    enabled: true
    fullTextFields: ["message"]


