CREATE TABLE IF NOT EXISTS "phone_home_data"
(
    "@timestamp"              DateTime64(3) DEFAULT now64(),
    "attributes_string_key"   Array(String),
    "attributes_string_value" Array(String),

    "quesma_customer" Nullable(String),
    "top_user_agents"         Array(String),
    "started_at" Nullable(Int64),
    "hostname" Nullable(String),
    "number_of_panics" Nullable(Int64),
    "quesma_version" Nullable(String),
    "instanceId" Nullable(String),
    "runtime::memory_used" Nullable(Int64),
    "runtime::memory_available" Nullable(Int64),
    "taken_at" Nullable(Int64),
    "report_type" Nullable(String),

    "clickhouse::open_connection" Nullable(Int64),
    "clickhouse::max_open_connection" Nullable(Int64),
    "clickhouse::server_version" Nullable(String),
    "clickhouse::status" Nullable(String),
    "clickhouse::number_of_rows" Nullable(Int64),
    "clickhouse::disk_space" Nullable(Int64),

    "clickhouse_queries::count" Nullable(Int64),
    "clickhouse_queries::avg_time_sec" Nullable(Float64),
    "clickhouse_queries::failed" Nullable(Int64),
    "clickhouse_queries::over_thresholds::10" Nullable(Int64),
    "clickhouse_queries::over_thresholds::30" Nullable(Int64),
    "clickhouse_queries::over_thresholds::5" Nullable(Int64),
    "clickhouse_queries::over_thresholds::60" Nullable(Int64),
    "clickhouse_queries::over_thresholds::1" Nullable(Int64),
    "clickhouse_queries::percentiles::50" Nullable(Float64),
    "clickhouse_queries::percentiles::75" Nullable(Float64),
    "clickhouse_queries::percentiles::95" Nullable(Float64),
    "clickhouse_queries::percentiles::25" Nullable(Float64),
    "clickhouse_queries::percentiles::5" Nullable(Float64),

    "clickhouse_inserts::count" Nullable(Int64),
    "clickhouse_inserts::avg_time_sec" Nullable(Float64),
    "clickhouse_inserts::failed" Nullable(Int64),

    "clickhouse_inserts::percentiles::25" Nullable(Float64),
    "clickhouse_inserts::percentiles::5" Nullable(Float64),
    "clickhouse_inserts::percentiles::50" Nullable(Float64),
    "clickhouse_inserts::percentiles::75" Nullable(Float64),
    "clickhouse_inserts::percentiles::95" Nullable(Float64),

    "clickhouse_inserts::over_thresholds::60" Nullable(Int64),
    "clickhouse_inserts::over_thresholds::1" Nullable(Int64),
    "clickhouse_inserts::over_thresholds::10" Nullable(Int64),
    "clickhouse_inserts::over_thresholds::30" Nullable(Int64),
    "clickhouse_inserts::over_thresholds::5" Nullable(Int64),

    "elasticsearch::status" Nullable(String),
    "elasticsearch::number_of_docs" Nullable(Int64),
    "elasticsearch::size" Nullable(Int64),
    "elasticsearch::server_version" Nullable(String),

    "elastic_read_requests::count" Nullable(Int64),
    "elastic_read_requests::avg_time_sec" Nullable(Float64),
    "elastic_read_requests::failed" Nullable(Int64),
    "elastic_read_requests::over_thresholds::30" Nullable(Int64),
    "elastic_read_requests::over_thresholds::5" Nullable(Int64),
    "elastic_read_requests::over_thresholds::60" Nullable(Int64),
    "elastic_read_requests::over_thresholds::1" Nullable(Int64),
    "elastic_read_requests::over_thresholds::10" Nullable(Int64),
    "elastic_read_requests::percentiles::5" Nullable(Float64),
    "elastic_read_requests::percentiles::50" Nullable(Float64),
    "elastic_read_requests::percentiles::75" Nullable(Float64),
    "elastic_read_requests::percentiles::95" Nullable(Float64),
    "elastic_read_requests::percentiles::25" Nullable(Float64),


    "elastic_write_requests::count" Nullable(Int64),
    "elastic_write_requests::avg_time_sec" Nullable(Float64),
    "elastic_write_requests::failed" Nullable(Int64),

    "elastic_write_requests::over_thresholds::1" Nullable(Int64),
    "elastic_write_requests::over_thresholds::10" Nullable(Int64),
    "elastic_write_requests::over_thresholds::30" Nullable(Int64),
    "elastic_write_requests::over_thresholds::5" Nullable(Int64),
    "elastic_write_requests::over_thresholds::60" Nullable(Int64),
    "elastic_write_requests::percentiles::25" Nullable(Float64),
    "elastic_write_requests::percentiles::5" Nullable(Float64),
    "elastic_write_requests::percentiles::50" Nullable(Float64),
    "elastic_write_requests::percentiles::75" Nullable(Float64),
    "elastic_write_requests::percentiles::95" Nullable(Float64),


    "elastic_bypassed_read_requests::count" Nullable(Int64),
    "elastic_bypassed_read_requests::avg_time_sec" Nullable(Float64),
    "elastic_bypassed_read_requests::failed" Nullable(Int64),

    "elastic_bypassed_read_requests::over_thresholds::1" Nullable(Int64),
    "elastic_bypassed_read_requests::over_thresholds::10" Nullable(Int64),
    "elastic_bypassed_read_requests::over_thresholds::30" Nullable(Int64),
    "elastic_bypassed_read_requests::over_thresholds::5" Nullable(Int64),
    "elastic_bypassed_read_requests::over_thresholds::60" Nullable(Int64),
    "elastic_bypassed_read_requests::percentiles::5" Nullable(Float64),
    "elastic_bypassed_read_requests::percentiles::50" Nullable(Float64),
    "elastic_bypassed_read_requests::percentiles::75" Nullable(Float64),
    "elastic_bypassed_read_requests::percentiles::95" Nullable(Float64),
    "elastic_bypassed_read_requests::percentiles::25" Nullable(Float64),

    "elastic_bypassed_write_requests::count" Nullable(Int64),
    "elastic_bypassed_write_requests::avg_time_sec" Nullable(Float64),
    "elastic_bypassed_write_requests::failed" Nullable(Int64),

    "elastic_bypassed_write_requests::over_thresholds::1" Nullable(Int64),
    "elastic_bypassed_write_requests::over_thresholds::10" Nullable(Int64),
    "elastic_bypassed_write_requests::over_thresholds::30" Nullable(Int64),
    "elastic_bypassed_write_requests::over_thresholds::5" Nullable(Int64),
    "elastic_bypassed_write_requests::over_thresholds::60" Nullable(Int64),
    "elastic_bypassed_write_requests::percentiles::5" Nullable(Float64),
    "elastic_bypassed_write_requests::percentiles::50" Nullable(Float64),
    "elastic_bypassed_write_requests::percentiles::75" Nullable(Float64),
    "elastic_bypassed_write_requests::percentiles::95" Nullable(Float64),
    "elastic_bypassed_write_requests::percentiles::25" Nullable(Float64),

    "config_mode" Nullable(String),
    "top_errors"  Array(String),
    "build_hash" Nullable(String),
    "build_date" Nullable(DateTime64(3)),
    "number_of_failed_requests" Nullable(Int64),

    )
    ENGINE = MergeTree
    ORDER BY ("@timestamp")
    COMMENT 'Phone home data. Created by clean-clickhouse.'
