// Copyright Quesma, licensed under the Elastic License 2.0.
// SPDX-License-Identifier: Elastic-2.0

// This file contains code derived from:
//
// 1. sqlparse (Copyright (c) 2016, Andi Albrecht)
//    Licensed under BSD-3-Clause License
//    https://github.com/andialbrecht/sqlparse/blob/38c065b86ac43f76ffd319747e57096ed78bfa63/LICENSE

package dialect_sqlparse

import (
	"github.com/QuesmaOrg/quesma/quesma/parsers/sql/lexer/core"
	"maps"
)

// The following code block is based on KEYWORDS from sqlparse:
// https://github.com/andialbrecht/sqlparse/blob/38c065b86ac43f76ffd319747e57096ed78bfa63/sqlparse/keywords.py

var KEYWORDS = map[string]*core.TokenType{
	"ABORT":          &KeywordTokenType,
	"ABS":            &KeywordTokenType,
	"ABSOLUTE":       &KeywordTokenType,
	"ACCESS":         &KeywordTokenType,
	"ADA":            &KeywordTokenType,
	"ADD":            &KeywordTokenType,
	"ADMIN":          &KeywordTokenType,
	"AFTER":          &KeywordTokenType,
	"AGGREGATE":      &KeywordTokenType,
	"ALIAS":          &KeywordTokenType,
	"ALL":            &KeywordTokenType,
	"ALLOCATE":       &KeywordTokenType,
	"ANALYSE":        &KeywordTokenType,
	"ANALYZE":        &KeywordTokenType,
	"ANY":            &KeywordTokenType,
	"ARRAYLEN":       &KeywordTokenType,
	"ARE":            &KeywordTokenType,
	"ASENSITIVE":     &KeywordTokenType,
	"ASSERTION":      &KeywordTokenType,
	"ASSIGNMENT":     &KeywordTokenType,
	"ASYMMETRIC":     &KeywordTokenType,
	"AT":             &KeywordTokenType,
	"ATOMIC":         &KeywordTokenType,
	"AUDIT":          &KeywordTokenType,
	"AUTHORIZATION":  &KeywordTokenType,
	"AUTO_INCREMENT": &KeywordTokenType,
	"AVG":            &KeywordTokenType,

	"BACKWARD":   &KeywordTokenType,
	"BEFORE":     &KeywordTokenType,
	"BEGIN":      &KeywordTokenType,
	"BETWEEN":    &KeywordTokenType,
	"BITVAR":     &KeywordTokenType,
	"BIT_LENGTH": &KeywordTokenType,
	"BOTH":       &KeywordTokenType,
	"BREADTH":    &KeywordTokenType,

	// "C":&KeywordTokenType,  // most likely this is an alias
	"CACHE":                 &KeywordTokenType,
	"CALL":                  &KeywordTokenType,
	"CALLED":                &KeywordTokenType,
	"CARDINALITY":           &KeywordTokenType,
	"CASCADE":               &KeywordTokenType,
	"CASCADED":              &KeywordTokenType,
	"CAST":                  &KeywordTokenType,
	"CATALOG":               &KeywordTokenType,
	"CATALOG_NAME":          &KeywordTokenType,
	"CHAIN":                 &KeywordTokenType,
	"CHARACTERISTICS":       &KeywordTokenType,
	"CHARACTER_LENGTH":      &KeywordTokenType,
	"CHARACTER_SET_CATALOG": &KeywordTokenType,
	"CHARACTER_SET_NAME":    &KeywordTokenType,
	"CHARACTER_SET_SCHEMA":  &KeywordTokenType,
	"CHAR_LENGTH":           &KeywordTokenType,
	"CHARSET":               &KeywordTokenType,
	"CHECK":                 &KeywordTokenType,
	"CHECKED":               &KeywordTokenType,
	"CHECKPOINT":            &KeywordTokenType,
	"CLASS":                 &KeywordTokenType,
	"CLASS_ORIGIN":          &KeywordTokenType,
	"CLOB":                  &KeywordTokenType,
	"CLOSE":                 &KeywordTokenType,
	"CLUSTER":               &KeywordTokenType,
	"COALESCE":              &KeywordTokenType,
	"COBOL":                 &KeywordTokenType,
	"COLLATE":               &KeywordTokenType,
	"COLLATION":             &KeywordTokenType,
	"COLLATION_CATALOG":     &KeywordTokenType,
	"COLLATION_NAME":        &KeywordTokenType,
	"COLLATION_SCHEMA":      &KeywordTokenType,
	"COLLECT":               &KeywordTokenType,
	"COLUMN":                &KeywordTokenType,
	"COLUMN_NAME":           &KeywordTokenType,
	"COMPRESS":              &KeywordTokenType,
	"COMMAND_FUNCTION":      &KeywordTokenType,
	"COMMAND_FUNCTION_CODE": &KeywordTokenType,
	"COMMENT":               &KeywordTokenType,
	"COMMIT":                &DMLKeywordTokenType,
	"COMMITTED":             &KeywordTokenType,
	"COMPLETION":            &KeywordTokenType,
	"CONCURRENTLY":          &KeywordTokenType,
	"CONDITION_NUMBER":      &KeywordTokenType,
	"CONNECT":               &KeywordTokenType,
	"CONNECTION":            &KeywordTokenType,
	"CONNECTION_NAME":       &KeywordTokenType,
	"CONSTRAINT":            &KeywordTokenType,
	"CONSTRAINTS":           &KeywordTokenType,
	"CONSTRAINT_CATALOG":    &KeywordTokenType,
	"CONSTRAINT_NAME":       &KeywordTokenType,
	"CONSTRAINT_SCHEMA":     &KeywordTokenType,
	"CONSTRUCTOR":           &KeywordTokenType,
	"CONTAINS":              &KeywordTokenType,
	"CONTINUE":              &KeywordTokenType,
	"CONVERSION":            &KeywordTokenType,
	"CONVERT":               &KeywordTokenType,
	"COPY":                  &KeywordTokenType,
	"CORRESPONDING":         &KeywordTokenType,
	"COUNT":                 &KeywordTokenType,
	"CREATEDB":              &KeywordTokenType,
	"CREATEUSER":            &KeywordTokenType,
	"CROSS":                 &KeywordTokenType,
	"CUBE":                  &KeywordTokenType,
	"CURRENT":               &KeywordTokenType,
	"CURRENT_DATE":          &KeywordTokenType,
	"CURRENT_PATH":          &KeywordTokenType,
	"CURRENT_ROLE":          &KeywordTokenType,
	"CURRENT_TIME":          &KeywordTokenType,
	"CURRENT_TIMESTAMP":     &KeywordTokenType,
	"CURRENT_USER":          &KeywordTokenType,
	"CURSOR":                &KeywordTokenType,
	"CURSOR_NAME":           &KeywordTokenType,
	"CYCLE":                 &KeywordTokenType,

	"DATA":                        &KeywordTokenType,
	"DATABASE":                    &KeywordTokenType,
	"DATETIME_INTERVAL_CODE":      &KeywordTokenType,
	"DATETIME_INTERVAL_PRECISION": &KeywordTokenType,
	"DAY":                         &KeywordTokenType,
	"DEALLOCATE":                  &KeywordTokenType,
	"DECLARE":                     &KeywordTokenType,
	"DEFAULT":                     &KeywordTokenType,
	"DEFAULTS":                    &KeywordTokenType,
	"DEFERRABLE":                  &KeywordTokenType,
	"DEFERRED":                    &KeywordTokenType,
	"DEFINED":                     &KeywordTokenType,
	"DEFINER":                     &KeywordTokenType,
	"DELIMITER":                   &KeywordTokenType,
	"DELIMITERS":                  &KeywordTokenType,
	"DEREF":                       &KeywordTokenType,
	"DESCRIBE":                    &KeywordTokenType,
	"DESCRIPTOR":                  &KeywordTokenType,
	"DESTROY":                     &KeywordTokenType,
	"DESTRUCTOR":                  &KeywordTokenType,
	"DETERMINISTIC":               &KeywordTokenType,
	"DIAGNOSTICS":                 &KeywordTokenType,
	"DICTIONARY":                  &KeywordTokenType,
	"DISABLE":                     &KeywordTokenType,
	"DISCONNECT":                  &KeywordTokenType,
	"DISPATCH":                    &KeywordTokenType,
	"DIV":                         &OperatorTokenType,
	"DO":                          &KeywordTokenType,
	"DOMAIN":                      &KeywordTokenType,
	"DYNAMIC":                     &KeywordTokenType,
	"DYNAMIC_FUNCTION":            &KeywordTokenType,
	"DYNAMIC_FUNCTION_CODE":       &KeywordTokenType,

	"EACH":      &KeywordTokenType,
	"ENABLE":    &KeywordTokenType,
	"ENCODING":  &KeywordTokenType,
	"ENCRYPTED": &KeywordTokenType,
	"END-EXEC":  &KeywordTokenType,
	"ENGINE":    &KeywordTokenType,
	"EQUALS":    &KeywordTokenType,
	"ESCAPE":    &KeywordTokenType,
	"EVERY":     &KeywordTokenType,
	"EXCEPT":    &KeywordTokenType,
	"EXCEPTION": &KeywordTokenType,
	"EXCLUDING": &KeywordTokenType,
	"EXCLUSIVE": &KeywordTokenType,
	"EXEC":      &KeywordTokenType,
	"EXECUTE":   &KeywordTokenType,
	"EXISTING":  &KeywordTokenType,
	"EXISTS":    &KeywordTokenType,
	"EXPLAIN":   &KeywordTokenType,
	"EXTERNAL":  &KeywordTokenType,
	"EXTRACT":   &KeywordTokenType,

	"FALSE":    &KeywordTokenType,
	"FETCH":    &KeywordTokenType,
	"FILE":     &KeywordTokenType,
	"FINAL":    &KeywordTokenType,
	"FIRST":    &KeywordTokenType,
	"FORCE":    &KeywordTokenType,
	"FOREACH":  &KeywordTokenType,
	"FOREIGN":  &KeywordTokenType,
	"FORTRAN":  &KeywordTokenType,
	"FORWARD":  &KeywordTokenType,
	"FOUND":    &KeywordTokenType,
	"FREE":     &KeywordTokenType,
	"FREEZE":   &KeywordTokenType,
	"FULL":     &KeywordTokenType,
	"FUNCTION": &KeywordTokenType,

	// "G":&KeywordTokenType,
	"GENERAL":   &KeywordTokenType,
	"GENERATED": &KeywordTokenType,
	"GET":       &KeywordTokenType,
	"GLOBAL":    &KeywordTokenType,
	"GO":        &KeywordTokenType,
	"GOTO":      &KeywordTokenType,
	"GRANTED":   &KeywordTokenType,
	"GROUPING":  &KeywordTokenType,

	"HAVING":    &KeywordTokenType,
	"HIERARCHY": &KeywordTokenType,
	"HOLD":      &KeywordTokenType,
	"HOUR":      &KeywordTokenType,
	"HOST":      &KeywordTokenType,

	"IDENTIFIED": &KeywordTokenType,
	"IDENTITY":   &KeywordTokenType,
	"IGNORE":     &KeywordTokenType,
	"ILIKE":      &KeywordTokenType,
	"IMMEDIATE":  &KeywordTokenType,
	"IMMUTABLE":  &KeywordTokenType,

	"IMPLEMENTATION": &KeywordTokenType,
	"IMPLICIT":       &KeywordTokenType,
	"INCLUDING":      &KeywordTokenType,
	"INCREMENT":      &KeywordTokenType,
	"INDEX":          &KeywordTokenType,

	"INDICATOR":    &KeywordTokenType,
	"INFIX":        &KeywordTokenType,
	"INHERITS":     &KeywordTokenType,
	"INITIAL":      &KeywordTokenType,
	"INITIALIZE":   &KeywordTokenType,
	"INITIALLY":    &KeywordTokenType,
	"INOUT":        &KeywordTokenType,
	"INPUT":        &KeywordTokenType,
	"INSENSITIVE":  &KeywordTokenType,
	"INSTANTIABLE": &KeywordTokenType,
	"INSTEAD":      &KeywordTokenType,
	"INTERSECT":    &KeywordTokenType,
	"INTO":         &KeywordTokenType,
	"INVOKER":      &KeywordTokenType,
	"IS":           &KeywordTokenType,
	"ISNULL":       &KeywordTokenType,
	"ISOLATION":    &KeywordTokenType,
	"ITERATE":      &KeywordTokenType,

	// "K":&KeywordTokenType,
	"KEY":        &KeywordTokenType,
	"KEY_MEMBER": &KeywordTokenType,
	"KEY_TYPE":   &KeywordTokenType,

	"LANCOMPILER":    &KeywordTokenType,
	"LANGUAGE":       &KeywordTokenType,
	"LARGE":          &KeywordTokenType,
	"LAST":           &KeywordTokenType,
	"LATERAL":        &KeywordTokenType,
	"LEADING":        &KeywordTokenType,
	"LENGTH":         &KeywordTokenType,
	"LESS":           &KeywordTokenType,
	"LEVEL":          &KeywordTokenType,
	"LIMIT":          &KeywordTokenType,
	"LISTEN":         &KeywordTokenType,
	"LOAD":           &KeywordTokenType,
	"LOCAL":          &KeywordTokenType,
	"LOCALTIME":      &KeywordTokenType,
	"LOCALTIMESTAMP": &KeywordTokenType,
	"LOCATION":       &KeywordTokenType,
	"LOCATOR":        &KeywordTokenType,
	"LOCK":           &KeywordTokenType,
	"LOWER":          &KeywordTokenType,

	// "M":&KeywordTokenType,
	"MAP":                  &KeywordTokenType,
	"MATCH":                &KeywordTokenType,
	"MAXEXTENTS":           &KeywordTokenType,
	"MAXVALUE":             &KeywordTokenType,
	"MESSAGE_LENGTH":       &KeywordTokenType,
	"MESSAGE_OCTET_LENGTH": &KeywordTokenType,
	"MESSAGE_TEXT":         &KeywordTokenType,
	"METHOD":               &KeywordTokenType,
	"MINUTE":               &KeywordTokenType,
	"MINUS":                &KeywordTokenType,
	"MINVALUE":             &KeywordTokenType,
	"MOD":                  &KeywordTokenType,
	"MODE":                 &KeywordTokenType,
	"MODIFIES":             &KeywordTokenType,
	"MODIFY":               &KeywordTokenType,
	"MONTH":                &KeywordTokenType,
	"MORE":                 &KeywordTokenType,
	"MOVE":                 &KeywordTokenType,
	"MUMPS":                &KeywordTokenType,

	"NAMES":        &KeywordTokenType,
	"NATIONAL":     &KeywordTokenType,
	"NATURAL":      &KeywordTokenType,
	"NCHAR":        &KeywordTokenType,
	"NCLOB":        &KeywordTokenType,
	"NEW":          &KeywordTokenType,
	"NEXT":         &KeywordTokenType,
	"NO":           &KeywordTokenType,
	"NOAUDIT":      &KeywordTokenType,
	"NOCOMPRESS":   &KeywordTokenType,
	"NOCREATEDB":   &KeywordTokenType,
	"NOCREATEUSER": &KeywordTokenType,
	"NONE":         &KeywordTokenType,
	"NOT":          &KeywordTokenType,
	"NOTFOUND":     &KeywordTokenType,
	"NOTHING":      &KeywordTokenType,
	"NOTIFY":       &KeywordTokenType,
	"NOTNULL":      &KeywordTokenType,
	"NOWAIT":       &KeywordTokenType,
	"NULL":         &KeywordTokenType,
	"NULLABLE":     &KeywordTokenType,
	"NULLIF":       &KeywordTokenType,

	"OBJECT":       &KeywordTokenType,
	"OCTET_LENGTH": &KeywordTokenType,
	"OF":           &KeywordTokenType,
	"OFF":          &KeywordTokenType,
	"OFFLINE":      &KeywordTokenType,
	"OFFSET":       &KeywordTokenType,
	"OIDS":         &KeywordTokenType,
	"OLD":          &KeywordTokenType,
	"ONLINE":       &KeywordTokenType,
	"ONLY":         &KeywordTokenType,
	"OPEN":         &KeywordTokenType,
	"OPERATION":    &KeywordTokenType,
	"OPERATOR":     &KeywordTokenType,
	"OPTION":       &KeywordTokenType,
	"OPTIONS":      &KeywordTokenType,
	"ORDINALITY":   &KeywordTokenType,
	"OUT":          &KeywordTokenType,
	"OUTPUT":       &KeywordTokenType,
	"OVERLAPS":     &KeywordTokenType,
	"OVERLAY":      &KeywordTokenType,
	"OVERRIDING":   &KeywordTokenType,
	"OWNER":        &KeywordTokenType,

	"QUARTER": &KeywordTokenType,

	"PAD":                        &KeywordTokenType,
	"PARAMETER":                  &KeywordTokenType,
	"PARAMETERS":                 &KeywordTokenType,
	"PARAMETER_MODE":             &KeywordTokenType,
	"PARAMETER_NAME":             &KeywordTokenType,
	"PARAMETER_ORDINAL_POSITION": &KeywordTokenType,
	"PARAMETER_SPECIFIC_CATALOG": &KeywordTokenType,
	"PARAMETER_SPECIFIC_NAME":    &KeywordTokenType,
	"PARAMETER_SPECIFIC_SCHEMA":  &KeywordTokenType,
	"PARTIAL":                    &KeywordTokenType,
	"PASCAL":                     &KeywordTokenType,
	"PCTFREE":                    &KeywordTokenType,
	"PENDANT":                    &KeywordTokenType,
	"PLACING":                    &KeywordTokenType,
	"PLI":                        &KeywordTokenType,
	"POSITION":                   &KeywordTokenType,
	"POSTFIX":                    &KeywordTokenType,
	"PRECISION":                  &KeywordTokenType,
	"PREFIX":                     &KeywordTokenType,
	"PREORDER":                   &KeywordTokenType,
	"PREPARE":                    &KeywordTokenType,
	"PRESERVE":                   &KeywordTokenType,
	"PRIMARY":                    &KeywordTokenType,
	"PRIOR":                      &KeywordTokenType,
	"PRIVILEGES":                 &KeywordTokenType,
	"PROCEDURAL":                 &KeywordTokenType,
	"PROCEDURE":                  &KeywordTokenType,
	"PUBLIC":                     &KeywordTokenType,

	"RAISE":                 &KeywordTokenType,
	"RAW":                   &KeywordTokenType,
	"READ":                  &KeywordTokenType,
	"READS":                 &KeywordTokenType,
	"RECHECK":               &KeywordTokenType,
	"RECURSIVE":             &KeywordTokenType,
	"REF":                   &KeywordTokenType,
	"REFERENCES":            &KeywordTokenType,
	"REFERENCING":           &KeywordTokenType,
	"REINDEX":               &KeywordTokenType,
	"RELATIVE":              &KeywordTokenType,
	"RENAME":                &KeywordTokenType,
	"REPEATABLE":            &KeywordTokenType,
	"RESET":                 &KeywordTokenType,
	"RESOURCE":              &KeywordTokenType,
	"RESTART":               &KeywordTokenType,
	"RESTRICT":              &KeywordTokenType,
	"RESULT":                &KeywordTokenType,
	"RETURN":                &KeywordTokenType,
	"RETURNED_LENGTH":       &KeywordTokenType,
	"RETURNED_OCTET_LENGTH": &KeywordTokenType,
	"RETURNED_SQLSTATE":     &KeywordTokenType,
	"RETURNING":             &KeywordTokenType,
	"RETURNS":               &KeywordTokenType,
	"RIGHT":                 &KeywordTokenType,
	"ROLE":                  &KeywordTokenType,
	"ROLLBACK":              &DMLKeywordTokenType,
	"ROLLUP":                &KeywordTokenType,
	"ROUTINE":               &KeywordTokenType,
	"ROUTINE_CATALOG":       &KeywordTokenType,
	"ROUTINE_NAME":          &KeywordTokenType,
	"ROUTINE_SCHEMA":        &KeywordTokenType,
	"ROWS":                  &KeywordTokenType,
	"ROW_COUNT":             &KeywordTokenType,
	"RULE":                  &KeywordTokenType,

	"SAVE_POINT":    &KeywordTokenType,
	"SCALE":         &KeywordTokenType,
	"SCHEMA":        &KeywordTokenType,
	"SCHEMA_NAME":   &KeywordTokenType,
	"SCOPE":         &KeywordTokenType,
	"SCROLL":        &KeywordTokenType,
	"SEARCH":        &KeywordTokenType,
	"SECOND":        &KeywordTokenType,
	"SECURITY":      &KeywordTokenType,
	"SELF":          &KeywordTokenType,
	"SENSITIVE":     &KeywordTokenType,
	"SEQUENCE":      &KeywordTokenType,
	"SERIALIZABLE":  &KeywordTokenType,
	"SERVER_NAME":   &KeywordTokenType,
	"SESSION":       &KeywordTokenType,
	"SESSION_USER":  &KeywordTokenType,
	"SETOF":         &KeywordTokenType,
	"SETS":          &KeywordTokenType,
	"SHARE":         &KeywordTokenType,
	"SHOW":          &KeywordTokenType,
	"SIMILAR":       &KeywordTokenType,
	"SIMPLE":        &KeywordTokenType,
	"SIZE":          &KeywordTokenType,
	"SOME":          &KeywordTokenType,
	"SOURCE":        &KeywordTokenType,
	"SPACE":         &KeywordTokenType,
	"SPECIFIC":      &KeywordTokenType,
	"SPECIFICTYPE":  &KeywordTokenType,
	"SPECIFIC_NAME": &KeywordTokenType,
	"SQL":           &KeywordTokenType,
	"SQLBUF":        &KeywordTokenType,
	"SQLCODE":       &KeywordTokenType,
	"SQLERROR":      &KeywordTokenType,
	"SQLEXCEPTION":  &KeywordTokenType,
	"SQLSTATE":      &KeywordTokenType,
	"SQLWARNING":    &KeywordTokenType,
	"STABLE":        &KeywordTokenType,
	"START":         &DMLKeywordTokenType,
	// "STATE":&KeywordTokenType,
	"STATEMENT":       &KeywordTokenType,
	"STATIC":          &KeywordTokenType,
	"STATISTICS":      &KeywordTokenType,
	"STDIN":           &KeywordTokenType,
	"STDOUT":          &KeywordTokenType,
	"STORAGE":         &KeywordTokenType,
	"STRICT":          &KeywordTokenType,
	"STRUCTURE":       &KeywordTokenType,
	"STYPE":           &KeywordTokenType,
	"SUBCLASS_ORIGIN": &KeywordTokenType,
	"SUBLIST":         &KeywordTokenType,
	"SUBSTRING":       &KeywordTokenType,
	"SUCCESSFUL":      &KeywordTokenType,
	"SUM":             &KeywordTokenType,
	"SYMMETRIC":       &KeywordTokenType,
	"SYNONYM":         &KeywordTokenType,
	"SYSID":           &KeywordTokenType,
	"SYSTEM":          &KeywordTokenType,
	"SYSTEM_USER":     &KeywordTokenType,

	"TABLE":                    &KeywordTokenType,
	"TABLE_NAME":               &KeywordTokenType,
	"TEMP":                     &KeywordTokenType,
	"TEMPLATE":                 &KeywordTokenType,
	"TEMPORARY":                &KeywordTokenType,
	"TERMINATE":                &KeywordTokenType,
	"THAN":                     &KeywordTokenType,
	"TIMESTAMP":                &KeywordTokenType,
	"TIMEZONE_HOUR":            &KeywordTokenType,
	"TIMEZONE_MINUTE":          &KeywordTokenType,
	"TO":                       &KeywordTokenType,
	"TOAST":                    &KeywordTokenType,
	"TRAILING":                 &KeywordTokenType,
	"TRANSATION":               &KeywordTokenType,
	"TRANSACTIONS_COMMITTED":   &KeywordTokenType,
	"TRANSACTIONS_ROLLED_BACK": &KeywordTokenType,
	"TRANSATION_ACTIVE":        &KeywordTokenType,
	"TRANSFORM":                &KeywordTokenType,
	"TRANSFORMS":               &KeywordTokenType,
	"TRANSLATE":                &KeywordTokenType,
	"TRANSLATION":              &KeywordTokenType,
	"TREAT":                    &KeywordTokenType,
	"TRIGGER":                  &KeywordTokenType,
	"TRIGGER_CATALOG":          &KeywordTokenType,
	"TRIGGER_NAME":             &KeywordTokenType,
	"TRIGGER_SCHEMA":           &KeywordTokenType,
	"TRIM":                     &KeywordTokenType,
	"TRUE":                     &KeywordTokenType,
	"TRUSTED":                  &KeywordTokenType,
	"TYPE":                     &KeywordTokenType,

	"UID":                       &KeywordTokenType,
	"UNCOMMITTED":               &KeywordTokenType,
	"UNDER":                     &KeywordTokenType,
	"UNENCRYPTED":               &KeywordTokenType,
	"UNION":                     &KeywordTokenType,
	"UNIQUE":                    &KeywordTokenType,
	"UNKNOWN":                   &KeywordTokenType,
	"UNLISTEN":                  &KeywordTokenType,
	"UNNAMED":                   &KeywordTokenType,
	"UNNEST":                    &KeywordTokenType,
	"UNTIL":                     &KeywordTokenType,
	"UPPER":                     &KeywordTokenType,
	"USAGE":                     &KeywordTokenType,
	"USE":                       &KeywordTokenType,
	"USER":                      &KeywordTokenType,
	"USER_DEFINED_TYPE_CATALOG": &KeywordTokenType,
	"USER_DEFINED_TYPE_NAME":    &KeywordTokenType,
	"USER_DEFINED_TYPE_SCHEMA":  &KeywordTokenType,
	"USING":                     &KeywordTokenType,

	"VACUUM":    &KeywordTokenType,
	"VALID":     &KeywordTokenType,
	"VALIDATE":  &KeywordTokenType,
	"VALIDATOR": &KeywordTokenType,
	"VALUES":    &KeywordTokenType,
	"VARIABLE":  &KeywordTokenType,
	"VERBOSE":   &KeywordTokenType,
	"VERSION":   &KeywordTokenType,
	"VIEW":      &KeywordTokenType,
	"VOLATILE":  &KeywordTokenType,

	"WEEK":     &KeywordTokenType,
	"WHENEVER": &KeywordTokenType,
	"WITH":     &CTEKeywordTokenType,
	"WITHOUT":  &KeywordTokenType,
	"WORK":     &KeywordTokenType,
	"WRITE":    &KeywordTokenType,

	"YEAR": &KeywordTokenType,

	"ZONE": &KeywordTokenType,

	// Name.Builtin
	"ARRAY":          &BuiltinNameTokenType,
	"BIGINT":         &BuiltinNameTokenType,
	"BINARY":         &BuiltinNameTokenType,
	"BIT":            &BuiltinNameTokenType,
	"BLOB":           &BuiltinNameTokenType,
	"BOOLEAN":        &BuiltinNameTokenType,
	"CHAR":           &BuiltinNameTokenType,
	"CHARACTER":      &BuiltinNameTokenType,
	"DATE":           &BuiltinNameTokenType,
	"DEC":            &BuiltinNameTokenType,
	"DECIMAL":        &BuiltinNameTokenType,
	"FILE_TYPE":      &BuiltinNameTokenType,
	"FLOAT":          &BuiltinNameTokenType,
	"INT":            &BuiltinNameTokenType,
	"INT8":           &BuiltinNameTokenType,
	"INTEGER":        &BuiltinNameTokenType,
	"INTERVAL":       &BuiltinNameTokenType,
	"LONG":           &BuiltinNameTokenType,
	"NATURALN":       &BuiltinNameTokenType,
	"NVARCHAR":       &BuiltinNameTokenType,
	"NUMBER":         &BuiltinNameTokenType,
	"NUMERIC":        &BuiltinNameTokenType,
	"PLS_INTEGER":    &BuiltinNameTokenType,
	"POSITIVE":       &BuiltinNameTokenType,
	"POSITIVEN":      &BuiltinNameTokenType,
	"REAL":           &BuiltinNameTokenType,
	"ROWID":          &BuiltinNameTokenType,
	"ROWLABEL":       &BuiltinNameTokenType,
	"ROWNUM":         &BuiltinNameTokenType,
	"SERIAL":         &BuiltinNameTokenType,
	"SERIAL8":        &BuiltinNameTokenType,
	"SIGNED":         &BuiltinNameTokenType,
	"SIGNTYPE":       &BuiltinNameTokenType,
	"SIMPLE_DOUBLE":  &BuiltinNameTokenType,
	"SIMPLE_FLOAT":   &BuiltinNameTokenType,
	"SIMPLE_INTEGER": &BuiltinNameTokenType,
	"SMALLINT":       &BuiltinNameTokenType,
	"SYS_REFCURSOR":  &BuiltinNameTokenType,
	"SYSDATE":        &NameTokenType,
	"TEXT":           &BuiltinNameTokenType,
	"TINYINT":        &BuiltinNameTokenType,
	"UNSIGNED":       &BuiltinNameTokenType,
	"UROWID":         &BuiltinNameTokenType,
	"UTL_FILE":       &BuiltinNameTokenType,
	"VARCHAR":        &BuiltinNameTokenType,
	"VARCHAR2":       &BuiltinNameTokenType,
	"VARYING":        &BuiltinNameTokenType,
}

var KEYWORDS_COMMON = map[string]*core.TokenType{
	"SELECT":   &DMLKeywordTokenType,
	"INSERT":   &DMLKeywordTokenType,
	"DELETE":   &DMLKeywordTokenType,
	"UPDATE":   &DMLKeywordTokenType,
	"UPSERT":   &DMLKeywordTokenType,
	"REPLACE":  &DMLKeywordTokenType,
	"MERGE":    &DMLKeywordTokenType,
	"DROP":     &DDLKeywordTokenType,
	"CREATE":   &DDLKeywordTokenType,
	"ALTER":    &DDLKeywordTokenType,
	"TRUNCATE": &DDLKeywordTokenType,
	"GRANT":    &DCLKeywordTokenType,
	"REVOKE":   &DCLKeywordTokenType,

	"WHERE":         &KeywordTokenType,
	"FROM":          &KeywordTokenType,
	"INNER":         &KeywordTokenType,
	"JOIN":          &KeywordTokenType,
	"STRAIGHT_JOIN": &KeywordTokenType,
	"AND":           &KeywordTokenType,
	"OR":            &KeywordTokenType,
	"LIKE":          &KeywordTokenType,
	"ON":            &KeywordTokenType,
	"IN":            &KeywordTokenType,
	"SET":           &KeywordTokenType,

	"BY":    &KeywordTokenType,
	"GROUP": &KeywordTokenType,
	"ORDER": &KeywordTokenType,
	"LEFT":  &KeywordTokenType,
	"OUTER": &KeywordTokenType,
	"FULL":  &KeywordTokenType,

	"IF":    &KeywordTokenType,
	"END":   &KeywordTokenType,
	"THEN":  &KeywordTokenType,
	"LOOP":  &KeywordTokenType,
	"AS":    &KeywordTokenType,
	"ELSE":  &KeywordTokenType,
	"FOR":   &KeywordTokenType,
	"WHILE": &KeywordTokenType,

	"CASE":     &KeywordTokenType,
	"WHEN":     &KeywordTokenType,
	"MIN":      &KeywordTokenType,
	"MAX":      &KeywordTokenType,
	"DISTINCT": &KeywordTokenType,
}

var KEYWORDS_ORACLE = map[string]*core.TokenType{
	"ARCHIVE":    &KeywordTokenType,
	"ARCHIVELOG": &KeywordTokenType,

	"BACKUP": &KeywordTokenType,
	"BECOME": &KeywordTokenType,
	"BLOCK":  &KeywordTokenType,
	"BODY":   &KeywordTokenType,

	"CANCEL":      &KeywordTokenType,
	"CHANGE":      &KeywordTokenType,
	"COMPILE":     &KeywordTokenType,
	"CONTENTS":    &KeywordTokenType,
	"CONTROLFILE": &KeywordTokenType,

	"DATAFILE": &KeywordTokenType,
	"DBA":      &KeywordTokenType,
	"DISMOUNT": &KeywordTokenType,
	"DOUBLE":   &KeywordTokenType,
	"DUMP":     &KeywordTokenType,

	"ELSIF":      &KeywordTokenType,
	"EVENTS":     &KeywordTokenType,
	"EXCEPTIONS": &KeywordTokenType,
	"EXPLAIN":    &KeywordTokenType,
	"EXTENT":     &KeywordTokenType,
	"EXTERNALLY": &KeywordTokenType,

	"FLUSH":     &KeywordTokenType,
	"FREELIST":  &KeywordTokenType,
	"FREELISTS": &KeywordTokenType,

	// groups seems too common as table name
	// "GROUPS":&KeywordTokenType,

	"INDICATOR": &KeywordTokenType,
	"INITRANS":  &KeywordTokenType,
	"INSTANCE":  &KeywordTokenType,

	"LAYER":   &KeywordTokenType,
	"LINK":    &KeywordTokenType,
	"LISTS":   &KeywordTokenType,
	"LOGFILE": &KeywordTokenType,

	"MANAGE":        &KeywordTokenType,
	"MANUAL":        &KeywordTokenType,
	"MAXDATAFILES":  &KeywordTokenType,
	"MAXINSTANCES":  &KeywordTokenType,
	"MAXLOGFILES":   &KeywordTokenType,
	"MAXLOGHISTORY": &KeywordTokenType,
	"MAXLOGMEMBERS": &KeywordTokenType,
	"MAXTRANS":      &KeywordTokenType,
	"MINEXTENTS":    &KeywordTokenType,
	"MODULE":        &KeywordTokenType,
	"MOUNT":         &KeywordTokenType,

	"NOARCHIVELOG": &KeywordTokenType,
	"NOCACHE":      &KeywordTokenType,
	"NOCYCLE":      &KeywordTokenType,
	"NOMAXVALUE":   &KeywordTokenType,
	"NOMINVALUE":   &KeywordTokenType,
	"NOORDER":      &KeywordTokenType,
	"NORESETLOGS":  &KeywordTokenType,
	"NORMAL":       &KeywordTokenType,
	"NOSORT":       &KeywordTokenType,

	"OPTIMAL": &KeywordTokenType,
	"OWN":     &KeywordTokenType,

	"PACKAGE":     &KeywordTokenType,
	"PARALLEL":    &KeywordTokenType,
	"PCTINCREASE": &KeywordTokenType,
	"PCTUSED":     &KeywordTokenType,
	"PLAN":        &KeywordTokenType,
	"PRIVATE":     &KeywordTokenType,
	"PROFILE":     &KeywordTokenType,

	"QUOTA": &KeywordTokenType,

	"RECOVER":    &KeywordTokenType,
	"RESETLOGS":  &KeywordTokenType,
	"RESTRICTED": &KeywordTokenType,
	"REUSE":      &KeywordTokenType,
	"ROLES":      &KeywordTokenType,

	"SAVEPOINT":    &KeywordTokenType,
	"SCN":          &KeywordTokenType,
	"SECTION":      &KeywordTokenType,
	"SEGMENT":      &KeywordTokenType,
	"SHARED":       &KeywordTokenType,
	"SNAPSHOT":     &KeywordTokenType,
	"SORT":         &KeywordTokenType,
	"STATEMENT_ID": &KeywordTokenType,
	"STOP":         &KeywordTokenType,
	"SWITCH":       &KeywordTokenType,

	"TABLES":      &KeywordTokenType,
	"TABLESPACE":  &KeywordTokenType,
	"THREAD":      &KeywordTokenType,
	"TIME":        &KeywordTokenType,
	"TRACING":     &KeywordTokenType,
	"TRANSACTION": &KeywordTokenType,
	"TRIGGERS":    &KeywordTokenType,

	"UNLIMITED": &KeywordTokenType,
	"UNLOCK":    &KeywordTokenType,
}

// MySQL
var KEYWORDS_MYSQL = map[string]*core.TokenType{
	"ROW": &KeywordTokenType,
}

// PostgreSQL Syntax
var KEYWORDS_PLPGSQL = map[string]*core.TokenType{
	"CONFLICT":      &KeywordTokenType,
	"WINDOW":        &KeywordTokenType,
	"PARTITION":     &KeywordTokenType,
	"OVER":          &KeywordTokenType,
	"PERFORM":       &KeywordTokenType,
	"NOTICE":        &KeywordTokenType,
	"PLPGSQL":       &KeywordTokenType,
	"INHERIT":       &KeywordTokenType,
	"INDEXES":       &KeywordTokenType,
	"ON_ERROR_STOP": &KeywordTokenType,
	"EXTENSION":     &KeywordTokenType,

	"BYTEA":             &KeywordTokenType,
	"BIGSERIAL":         &KeywordTokenType,
	"BIT VARYING":       &KeywordTokenType,
	"BOX":               &KeywordTokenType,
	"CHARACTER":         &KeywordTokenType,
	"CHARACTER VARYING": &KeywordTokenType,
	"CIDR":              &KeywordTokenType,
	"CIRCLE":            &KeywordTokenType,
	"DOUBLE PRECISION":  &KeywordTokenType,
	"INET":              &KeywordTokenType,
	"JSON":              &KeywordTokenType,
	"JSONB":             &KeywordTokenType,
	"LINE":              &KeywordTokenType,
	"LSEG":              &KeywordTokenType,
	"MACADDR":           &KeywordTokenType,
	"MONEY":             &KeywordTokenType,
	"PATH":              &KeywordTokenType,
	"PG_LSN":            &KeywordTokenType,
	"POINT":             &KeywordTokenType,
	"POLYGON":           &KeywordTokenType,
	"SMALLSERIAL":       &KeywordTokenType,
	"TSQUERY":           &KeywordTokenType,
	"TSVECTOR":          &KeywordTokenType,
	"TXID_SNAPSHOT":     &KeywordTokenType,
	"UUID":              &KeywordTokenType,
	"XML":               &KeywordTokenType,

	"FOR":  &KeywordTokenType,
	"IN":   &KeywordTokenType,
	"LOOP": &KeywordTokenType,
}

// Hive Syntax
var KEYWORDS_HQL = map[string]*core.TokenType{
	"EXPLODE":    &KeywordTokenType,
	"DIRECTORY":  &KeywordTokenType,
	"DISTRIBUTE": &KeywordTokenType,
	"INCLUDE":    &KeywordTokenType,
	"LOCATE":     &KeywordTokenType,
	"OVERWRITE":  &KeywordTokenType,
	"POSEXPLODE": &KeywordTokenType,

	"ARRAY_CONTAINS":  &KeywordTokenType,
	"CMP":             &KeywordTokenType,
	"COLLECT_LIST":    &KeywordTokenType,
	"CONCAT":          &KeywordTokenType,
	"CONDITION":       &KeywordTokenType,
	"DATE_ADD":        &KeywordTokenType,
	"DATE_SUB":        &KeywordTokenType,
	"DECODE":          &KeywordTokenType,
	"DBMS_OUTPUT":     &KeywordTokenType,
	"ELEMENTS":        &KeywordTokenType,
	"EXCHANGE":        &KeywordTokenType,
	"EXTENDED":        &KeywordTokenType,
	"FLOOR":           &KeywordTokenType,
	"FOLLOWING":       &KeywordTokenType,
	"FROM_UNIXTIME":   &KeywordTokenType,
	"FTP":             &KeywordTokenType,
	"HOUR":            &KeywordTokenType,
	"INLINE":          &KeywordTokenType,
	"INSTR":           &KeywordTokenType,
	"LEN":             &KeywordTokenType,
	"MAP":             &BuiltinNameTokenType,
	"MAXELEMENT":      &KeywordTokenType,
	"MAXINDEX":        &KeywordTokenType,
	"MAX_PART_DATE":   &KeywordTokenType,
	"MAX_PART_INT":    &KeywordTokenType,
	"MAX_PART_STRING": &KeywordTokenType,
	"MINELEMENT":      &KeywordTokenType,
	"MININDEX":        &KeywordTokenType,
	"MIN_PART_DATE":   &KeywordTokenType,
	"MIN_PART_INT":    &KeywordTokenType,
	"MIN_PART_STRING": &KeywordTokenType,
	"NOW":             &KeywordTokenType,
	"NVL":             &KeywordTokenType,
	"NVL2":            &KeywordTokenType,
	"PARSE_URL_TUPLE": &KeywordTokenType,
	"PART_LOC":        &KeywordTokenType,
	"PART_COUNT":      &KeywordTokenType,
	"PART_COUNT_BY":   &KeywordTokenType,
	"PRINT":           &KeywordTokenType,
	"PUT_LINE":        &KeywordTokenType,
	"RANGE":           &KeywordTokenType,
	"REDUCE":          &KeywordTokenType,
	"REGEXP_REPLACE":  &KeywordTokenType,
	"RESIGNAL":        &KeywordTokenType,
	"RTRIM":           &KeywordTokenType,
	"SIGN":            &KeywordTokenType,
	"SIGNAL":          &KeywordTokenType,
	"SIN":             &KeywordTokenType,
	"SPLIT":           &KeywordTokenType,
	"SQRT":            &KeywordTokenType,
	"STACK":           &KeywordTokenType,
	"STR":             &KeywordTokenType,
	"STRING":          &BuiltinNameTokenType,
	"STRUCT":          &BuiltinNameTokenType,
	"SUBSTR":          &KeywordTokenType,
	"SUMMARY":         &KeywordTokenType,
	"TBLPROPERTIES":   &KeywordTokenType,
	"TIMESTAMP":       &BuiltinNameTokenType,
	"TIMESTAMP_ISO":   &KeywordTokenType,
	"TO_CHAR":         &KeywordTokenType,
	"TO_DATE":         &KeywordTokenType,
	"TO_TIMESTAMP":    &KeywordTokenType,
	"TRUNC":           &KeywordTokenType,
	"UNBOUNDED":       &KeywordTokenType,
	"UNIQUEJOIN":      &KeywordTokenType,
	"UNIX_TIMESTAMP":  &KeywordTokenType,
	"UTC_TIMESTAMP":   &KeywordTokenType,
	"VIEWS":           &KeywordTokenType,

	"EXIT":  &KeywordTokenType,
	"BREAK": &KeywordTokenType,
	"LEAVE": &KeywordTokenType,
}

var KEYWORDS_MSACCESS = map[string]*core.TokenType{
	"DISTINCTROW": &KeywordTokenType,
}

var KEYWORDS_SNOWFLAKE = map[string]*core.TokenType{
	"ACCOUNT":      &KeywordTokenType,
	"GSCLUSTER":    &KeywordTokenType,
	"ISSUE":        &KeywordTokenType,
	"ORGANIZATION": &KeywordTokenType,
	"PIVOT":        &KeywordTokenType,
	"QUALIFY":      &KeywordTokenType,
	"REGEXP":       &KeywordTokenType,
	"RLIKE":        &KeywordTokenType,
	"SAMPLE":       &KeywordTokenType,
	"TRY_CAST":     &KeywordTokenType,
	"UNPIVOT":      &KeywordTokenType,

	"VARIANT": &BuiltinNameTokenType,
}

var KEYWORDS_BIGQUERY = map[string]*core.TokenType{
	"ASSERT_ROWS_MODIFIED": &KeywordTokenType,
	"DEFINE":               &KeywordTokenType,
	"ENUM":                 &KeywordTokenType,
	"HASH":                 &KeywordTokenType,
	"LOOKUP":               &KeywordTokenType,
	"PRECEDING":            &KeywordTokenType,
	"PROTO":                &KeywordTokenType,
	"RESPECT":              &KeywordTokenType,
	"TABLESAMPLE":          &KeywordTokenType,

	"BIGNUMERIC": &BuiltinNameTokenType,
}

var ALL_KEYWORDS = func() map[string]*core.TokenType {
	merged := make(map[string]*core.TokenType)
	maps.Copy(merged, KEYWORDS)
	maps.Copy(merged, KEYWORDS_COMMON)
	maps.Copy(merged, KEYWORDS_ORACLE)
	maps.Copy(merged, KEYWORDS_MYSQL)
	maps.Copy(merged, KEYWORDS_PLPGSQL)
	maps.Copy(merged, KEYWORDS_HQL)
	maps.Copy(merged, KEYWORDS_MSACCESS)
	maps.Copy(merged, KEYWORDS_SNOWFLAKE)
	maps.Copy(merged, KEYWORDS_BIGQUERY)
	return merged
}()
