# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

elasticsearch:
  client:
    hosts: [ http://mitmproxy:8080 ]
  other_settings:
    username: elastic
    password: ${ELASTIC_PASSWORD}

logging:
  loglevel: INFO
  logformat: default
