package clickhouse

var NewRuntimeSchemas = make(map[string]SchemaMap)

// 27 schemas now.
var PredefinedTableSchemas = map[string]SchemaMap{
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_1": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_10": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt": nil,
				"scope":       nil,
				"startedAt":   nil,
				"state":       nil,
				"status":      nil,
				"taskType":    nil,
				"traceparent": nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_11": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_12": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"scope":        nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_13": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_14": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"scope":        nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_15": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_16": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt": nil,
				"scope":       nil,
				"startedAt":   nil,
				"state":       nil,
				"status":      nil,
				"taskType":    nil,
				"traceparent": nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_17": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_18": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"scope":        nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_19": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_2": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_20": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"scope":        nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_3": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_4": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_5": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_6": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt":  nil,
				"scope":        nil,
				"startedAt":    nil,
				"state":        nil,
				"stateVersion": nil,
				"status":       nil,
				"taskType":     nil,
				"traceparent":  nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_7": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_8": {
		"doc": SchemaMap{
			"task": SchemaMap{
				"attempts": nil,
				"ownerId":  nil,
				"params":   nil,
				"retryAt":  nil,
				"runAt":    nil,
				"schedule": SchemaMap{
					"interval": nil,
				},
				"scheduledAt": nil,
				"scope":       nil,
				"startedAt":   nil,
				"state":       nil,
				"status":      nil,
				"taskType":    nil,
				"traceparent": nil,
			},
			"updated_at": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_bulk?refresh=false&_source_includes=originId&require_alias=true_9": {
		"others":    nil,
		"timestamp": nil,
		"update": SchemaMap{
			"_id":             nil,
			"_index":          nil,
			"if_primary_term": nil,
			"if_seq_no":       nil,
		},
	},
	"/_bulk?refresh=false&require_alias=true_1": {
		"delete": SchemaMap{
			"_id":    nil,
			"_index": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_monitoring/bulk?system_id=kibana&system_api_version=7&interval=10000ms_1": {
		"index": SchemaMap{
			"_type": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_monitoring/bulk?system_id=kibana&system_api_version=7&interval=10000ms_2": {
		"concurrent_connections": nil,
		"elasticsearch_client": SchemaMap{
			"totalActiveSockets":  nil,
			"totalIdleSockets":    nil,
			"totalQueuedRequests": nil,
		},
		"kibana": SchemaMap{
			"host":              nil,
			"index":             nil,
			"name":              nil,
			"snapshot":          nil,
			"status":            nil,
			"transport_address": nil,
			"uuid":              nil,
			"version":           nil,
		},
		"os": SchemaMap{
			"cpu": SchemaMap{
				"cfs_period_micros": nil,
				"cfs_quota_micros":  nil,
				"control_group":     nil,
				"stat": SchemaMap{
					"number_of_elapsed_periods": nil,
					"number_of_times_throttled": nil,
					"time_throttled_nanos":      nil,
				},
			},
			"cpuacct": SchemaMap{
				"control_group": nil,
				"usage_nanos":   nil,
			},
			"distro":        nil,
			"distroRelease": nil,
			"load": SchemaMap{
				"`15m`": nil,
				"`1m`":  nil,
				"`5m`":  nil,
			},
			"memory": SchemaMap{
				"free_in_bytes":  nil,
				"total_in_bytes": nil,
				"used_in_bytes":  nil,
			},
			"platform":         nil,
			"platformRelease":  nil,
			"uptime_in_millis": nil,
		},
		"others": nil,
		"process": SchemaMap{
			"event_loop_delay": nil,
			"event_loop_delay_histogram": SchemaMap{
				"exceeds":       nil,
				"fromTimestamp": nil,
				"lastUpdatedAt": nil,
				"max":           nil,
				"mean":          nil,
				"min":           nil,
				"percentiles": SchemaMap{
					"`50`": nil,
					"`75`": nil,
					"`95`": nil,
					"`99`": nil,
				},
				"stddev": nil,
			},
			"event_loop_utilization": SchemaMap{
				"active":      nil,
				"idle":        nil,
				"utilization": nil,
			},
			"memory": SchemaMap{
				"heap": SchemaMap{
					"size_limit":     nil,
					"total_in_bytes": nil,
					"used_in_bytes":  nil,
				},
				"resident_set_size_in_bytes": nil,
			},
			"uptime_in_millis": nil,
		},
		"processes": nil,
		"requests": SchemaMap{
			"disconnects": nil,
			"total":       nil,
		},
		"response_times": SchemaMap{
			"average": nil,
			"max":     nil,
		},
		"timestamp": nil,
	},
	"/_monitoring/bulk?system_id=kibana&system_api_version=7&interval=10000ms_3": {
		"index": SchemaMap{
			"_type": nil,
		},
		"others":    nil,
		"timestamp": nil,
	},
	"/_monitoring/bulk?system_id=kibana&system_api_version=7&interval=10000ms_4": {
		"kibana": SchemaMap{
			"host":              nil,
			"index":             nil,
			"locale":            nil,
			"name":              nil,
			"port":              nil,
			"snapshot":          nil,
			"status":            nil,
			"transport_address": nil,
			"uuid":              nil,
			"version":           nil,
		},
		"others":    nil,
		"timestamp": nil,
		"xpack": SchemaMap{
			"default_admin_email": nil,
		},
	},
	"/logs-generic-default/_doc": {
		"host.name":    nil,
		"message":      nil,
		"others":       nil,
		"service.name": nil,
		"severity":     nil,
		"source":       nil,
		"timestamp":    nil,
	},
	"logs": {
		"message":   nil,
		"severity":  nil,
		"timestamp": nil,
	},
}
