version: "3.7"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
      - "--token"
      - ${CLOUDFLARED_TOKEN}
