version: "3.7"
services:
  quesma:
    build: ../quesma
    image: quesma:latest
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TCP_PORT=8080
      - LOGS_PATH=/var/quesma/logs
      - CLICKHOUSE_URL=${HYDROLIX_URL}
      - CLICKHOUSE_USER=${HYDROLIX_USER}
      - CLICKHOUSE_PASSWORD=${HYDROLIX_PASSWORD}
      - CLICKHOUSE_DATABASE=${HYDROLIX_DATABASE}
      - QUESMA_CONFIG=/var/quesma/config/hydrolix.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch
    ports:
      - "9999:9999"
      - "8080:8080"
    volumes:
      - ./quesma/config:/var/quesma/config
      - ./quesma/logs/:/var/quesma/logs
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx2G"
    ports:
      - "9201:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      start_period: 1m
      interval: 1s
      timeout: 1s
    deploy:
      resources:
        limits:
          memory: 4G
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    links:
      - "quesma"
    environment:
      ELASTICSEARCH_HOSTS: '["http://quesma:8080"]'
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTION_KEY: 'QUESMA' # Just to get rid of annoying ERROR in logs
    #      LOGGING_ROOT_LEVEL: 'debug'
    depends_on:
      quesma:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    restart: unless-stopped
    healthcheck:
      test: "curl -s http://localhost:5601/api/status >/dev/null || exit 1"
      start_period: 2m
      interval: 1s
      timeout: 1s
