version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    network_mode: "bridge"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      start_period: 1m
      interval: 1s
      timeout: 1s
    deploy:
      resources:
        limits:
          memory: 4G
  mitmproxy:
    image: mitmproxy/mitmproxy:10.1.5
    container_name: mitmproxy
    network_mode: "bridge"
    tty: true
    ports:
    - "6666:6666"
    - "8081:8081"
    command: >
      mitmweb --set termlog_verbosity=warn --no-web-open-browser --listen-port 6666 --web-host 0.0.0.0 --mode reverse:http://${HOST_IP}:8080/
    restart: unless-stopped
    volumes:
      - ./mitmproxy:/var/mitmproxy
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    links:
      - "mitmproxy"
    network_mode: "bridge"
    environment:
      ELASTICSEARCH_HOSTS: '["http://mitmproxy:6666"]'
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 'QUESMAQUESMAQUESMAQUESMAQUESMAQUESMAQUESMAQUESMA' # Just to get rid of annoying ERROR in logs
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    restart: unless-stopped
    healthcheck:
      test: "curl -s http://localhost:5601/api/status >/dev/null || exit 1"
      start_period: 2m
      interval: 1s
      timeout: 1s
  kibana-sidecar:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kiabana-sidecar
    network_mode: "bridge"
    restart: "no"
    links:
      - "kibana"
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ./kibana/:/local_mount
    command: ["/bin/bash", "-c", "/local_mount/add_sample_data.sh"]
  clickhouse:
    image: clickhouse/clickhouse-server:23.12.2.59-alpine
    container_name: clickhouse
    network_mode: "bridge"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/additional_config.xml:/etc/clickhouse-server/users.d/additional_config.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      start_period: 1m
