/kibana_sample_data_logs/_async_search?batched_reduce_size=64&ccs_minimize_roundtrips=true&wait_for_completion_timeout=200ms&keep_on_completion=true&keep_alive=60000ms&ignore_unavailable=true&preference=1718144139001
{
    "sort": [
        {
            "timestamp": {
                "order": "desc",
                "format": "strict_date_optional_time",
                "unmapped_type": "boolean"
            }
        },
        {
            "_doc": {
                "order": "desc",
                "unmapped_type": "boolean"
            }
        }
    ],
    "fields": [
        {
            "field": "*",
            "include_unmapped": "true"
        },
        {
            "field": "@timestamp",
            "format": "strict_date_optional_time"
        },
        {
            "field": "timestamp",
            "format": "strict_date_optional_time"
        },
        {
            "field": "utc_time",
            "format": "strict_date_optional_time"
        }
    ],
    "size": 500,
    "version": true,
    "script_fields": {},
    "stored_fields": [
        "*"
    ],
    "runtime_mappings": {
        "hour_of_day": {
            "type": "long",
            "script": {
                "source": "emit(doc['timestamp'].value.getHour());"
            }
        }
    },
    "_source": false,
    "query": {
        "bool": {
            "must": [],
            "filter": [
                {
                    "range": {
                        "timestamp": {
                            "format": "strict_date_optional_time",
                            "gte": "2024-02-27T23:15:49.450Z",
                            "lte": "2024-06-11T22:15:49.450Z"
                        }
                    }
                }
            ],
            "should": [],
            "must_not": []
        }
    },
    "highlight": {
        "pre_tags": [
            "@kibana-highlighted-field@"
        ],
        "post_tags": [
            "@/kibana-highlighted-field@"
        ],
        "fields": {
            "*": {}
        },
        "fragment_size": 2147483647
    },
    "track_total_hits": false
}