// Copyright Quesma, licensed under the Elastic License 2.0.
// SPDX-License-Identifier: Elastic-2.0
package elastic_query_dsl

import "github.com/QuesmaOrg/quesma/quesma/model"

// Structs used to represent the aggregation tree generated by first phase of pancake.
type pancakeAggregationTree struct {
	children    []*pancakeAggregationTreeNode
	whereClause model.Expr
}

type pancakeAggregationTreeNode struct {
	name            string
	queryType       model.QueryType
	selectedColumns []model.Expr

	// only for bucket aggregations
	children                []*pancakeAggregationTreeNode
	orderBy                 []model.OrderByExpr
	limit                   int // pancakeBucketAggregationNoLimit if none, only for bucket aggregation
	isKeyed                 bool
	filterOutEmptyKeyBucket bool

	metadata model.JsonMap
}
