mode: "dual-write-query-clickhouse"
licenseKey: "empty-license-key-that-is-just-ci"
port: 8080
indexes:
  kibana_sample_data_ecommerce:
    enabled: true
  kibana_sample_data_flights:
    enabled: true
  kibana_sample_data_logs:
    enabled: true
  logs-generic-default:
    enabled: true
  windows_logs:
    enabled: true
