mode: "dual-write-query-clickhouse"
connectors:
  ch:
    type: "clickhouse-os"
installationId: "just-Quesma-smoke-test-instance"
port: 8080
indexes:
  kibana_sample_data_ecommerce:
    enabled: true
  kibana_sample_data_flights:
    enabled: true
  kibana_sample_data_logs:
    enabled: true
  logs-generic-default:
    enabled: true
    fullTextFields: [ "message" ]
  windows_logs:   # Used for EQL e2e tests
    enabled: true
