mode: "dual-write-query-clickhouse"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  #url: "http://localhost:9200"
  call: false
  adminUrl: "http://localhost:5601"
clickhouse:
  url: "clickhouse://clickhouse:9000"
  adminUrl: "http://localhost:8123/play"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  path: "logs"
  level: "info"
  remoteUrl: "https://api.quesma.com/phone-home"
  disableFileLogging: false
indexes:
  e2e_table_1:
    enabled: true
    fullTextFields: [ "meme" ]