data-sources:
  logs-generic-default:
    enabled: true # optional, defaults to true
    fields:
      mappings:
        "timestamp":
          type: "alias"
          aliased-field: "@timestamp"
        "@timestamp":
          type: "date"
          primary-key: true
        "source":
          type: "keyword"
          match-keyword-and-text: true
        "message":
          type: "text"
        "service":
          type: "keyword"
      ignored: [ "foo1", "foo2" ]
    unknown-fields:
      strategy: "capture" # (capture, ignore, error)
      other-config: "" # strategy-specific
