# Default for local-dev.yml
mode: "dual-write-query-clickhouse"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
  adminUrl: "http://localhost:5601"
clickhouse:
  url: "clickhouse://clickhouse:9000"
  adminUrl: "http://localhost:8123/play"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  path: "logs"
  level: "info"
  remoteUrl: "https://api.quesma.com/phone-home"
  disableFileLogging: false
indexes:
  logs-generic-default:
    enabled: true
    static-schema:
      fields:
        "timestamp":
          type: "alias"
          aliased-field: "@timestamp"
        "@timestamp":
          type: "date"
          primary-key: true
        "message":
          type: "text"
        "service":
          type: "keyword"
        "severity":
          type: "keyword"
        "source":
          type: "keyword"
        "service.name":
          type: "keyword"
        "host.name":
          type: "keyword"
        "data_stream.dataset":
          type: "keyword"
        "data_stream.type":
          type: "keyword"
        "data_stream.namespace":
          type: "keyword"
      ignored:
        - "foobar17"
      unknown-fields:
        strategy: "capture"
        match-keyword-and-text: true
