# Default for local-dev.yml
mode: "dual-write-query-clickhouse"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
  adminUrl: "http://localhost:5601"
clickhouse:
  url: "clickhouse://clickhouse:9000"
  adminUrl: "http://localhost:8123/play"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  path: "logs"
  level: "info"
  remoteUrl: "https://api.quesma.com/phone-home"
  disableFileLogging: false

indexes:
  logs-generic-default:
    enabled: true
    primary-id: ["timestamp", "request_id"]
    mappings-overrides:
      fields:
        "timestamp":
          type: "alias"
          aliased-field: "@timestamp"
        "@timestamp":
          type: "date"
        "message":
          type: "text"
        "data_stream.dataset":
          column: "data_stream_dataset"
      ignored:
        - "foobar17"
      unknown-fields:
        strategy: "capture"
        match-keyword-and-text: true
