mode: "dual-write-query-clickhouse"
port: 8080  # public tcp port to listen for incoming traffic
licenseKey: "cdd749a3-e777-11ee-bcf8-0242ac150004"
elasticsearch:
  url: "http://localhost:9200"
logging:
  path: "logs"
  level: "info"
indexes:
  logs:
    enabled: true
    ignoredFields:
      unknown: true
    aliases:
      timestamp:
        source: "@timestamp"
        target: "reqTimeSec"
  siem:
    enabled: true
    ignoredFields:
      "responseHeaders": true
      "requestHeaders": true
      "botData": true
      "userRiskData": true
      "clientData": true

