quesma:
  mode: "dual-write-query-clickhouse"
  port: 8080  # public tcp port to listen for incoming traffic
  elasticsearch_url: "http://localhost:9200"
  clickhouse_url: "clickhouse://localhost:9000"
  logs_path: "logs"
  log_level: "info"
  index:
    211318:
      enabled: true
      fulltext_fields: ua,city_name

