# Default for local-dev.yml
mode: "dual-write-query-clickhouse"
licenseKey: "cdd749a3-e777-11ee-bcf8-0242ac150004"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
#clickhouse:   # this config is going to be removed, but for now let's just comment out
#  url: "clickhouse://localhost:9000"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  path: "logs"
  level: "info"
  remoteUrl: "https://api.quesma.com/phone-home"
  disableFileLogging: false
indexes:
  kibana_sample_data_ecommerce:
    enabled: true
  kibana_sample_data_flights:
    enabled: true
  kibana_sample_data_logs:
    enabled: true
    aliases:
      timestamp:
        source: "timestamp"
        target: "@timestamp"
  kafka-example-topic:
    enabled: true
  logs-generic-default:
    enabled: true
    fullTextFields: [ "message", "host.name" ]
  device_logs:
    enabled: true
    fullTextFields: [ "message" ]
  phone_home_logs:
    enabled: true
    fullTextFields: [ "message" ]
  windows_logs:
    enabled: true
  phone_home_data:
    enabled: true
    fullTextFields: [ "message" ]
