version: "3.7"
services:
  quesma:
    build: ../cmd
    image: quesma:nightly
    environment:
      - QUESMA_CONFIG_FILE=/mnt/ci-config.yaml
      - QUESMA_logging_path=/var/quesma/logs
      - QUESMA_logging_fileLogging=true
    depends_on:
      clickhouse:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "9999:9999"
      - "8080:8080"
      - "9200:8080"
    volumes:
      - ./quesma/logs/:/var/quesma/logs
      - ../examples/kibana-sample-data/quesma/config/local-dev.yaml:/mnt/ci-config.yaml
    restart: unless-stopped
  log-generator:
    build: log-generator
    image: log-generator:latest
    depends_on:
      quesma:
        condition: service_healthy
    links:
      - "quesma:mitmproxy"
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9201:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      start_period: 1m
      interval: 1s
      timeout: 1s
    deploy:
      resources:
        limits:
          memory: 4G
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      ELASTICSEARCH_HOSTS: '["http://quesma:8080"]'
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 'QUESMAQUESMAQUESMAQUESMAQUESMAQUESMAQUESMAQUESMA' # Just to get rid of annoying ERROR in logs
    depends_on:
      quesma:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    restart: unless-stopped
    healthcheck:
      test: "curl -s http://localhost:5601/api/status >/dev/null || exit 1"
      start_period: 2m
      interval: 1s
      timeout: 1s
  kibana-sidecar:
    image: docker.elastic.co/kibana/kibana:8.11.1
    restart: "no"
    environment:
      - LIMITED_DATASET=true
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ./kibana/:/local_mount
    command: ["/bin/bash", "-c", "/local_mount/add_sample_data.sh"]
  clickhouse:
    image: clickhouse/clickhouse-server:23.12.2.59-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/additional_config.xml:/etc/clickhouse-server/users.d/additional_config.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      start_period: 1m

