version: "3.7"
services:
  quesma:
    build: ../cmd
    image: quesma:nightly
    environment:
      - QUESMA_CONFIG_FILE=/mnt/ci-config.yaml
      - QUESMA_elasticsearch_url=http://elasticsearch:9200
      - QUESMA_port=8080
      - QUESMA_logging_path=/var/quesma/logs
      - QUESMA_installationId=old-e2e-test-run
      - QUESMA_connectors_my-clickhouse-connector_type=clickhouse-os
      - QUESMA_clickhouse_url=clickhouse://clickhouse:9000
      - QUESMA_logging_fileLogging=false
    depends_on:
      clickhouse:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "9999:9999"
      - "8080:8080"
      - "9200:8080"
    volumes:
      - ./quesma/config/ci-config.yaml:/mnt/ci-config.yaml
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9201:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      start_period: 1m
      interval: 1s
      timeout: 1s
    deploy:
      resources:
        limits:
          memory: 4G
  clickhouse:
    image: clickhouse/clickhouse-server:23.12.2.59-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/additional_config.xml:/etc/clickhouse-server/users.d/additional_config.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      start_period: 1m

