GET http://localhost:6666/panic
Content-Type: application/json

{
  "_source": false,
  "fields": [

  ],

  "query": {
    "bool": {
      "filter": [],
      "must": [],
      "must_not": [],
      "should": []
    }
  },
  "runtime_mappings": {},
  "script_fields": {},
  "size": 500,

  "stored_fields": [
    "*"
  ],
  "track_total_hits": false,
  "version": true
}


