POST http://localhost:8080/logs-*/_async_search?batched_reduce_size=64&ccs_minimize_roundtrips=true&wait_for_completion_timeout=200ms&keep_on_completion=false&keep_alive=60000ms&ignore_unavailable=true&allow_no_indices=true
user-agent: Kibana/8.11.1
x-elastic-product-origin: kibana
x-opaque-id: 75fec6c0-e47b-4c70-9143-cd8254398f05;kibana:application:logs:;application:logs:
x-elastic-client-meta: es=8.9.1p,js=18.18.2,t=8.3.3,hc=18.18.2
content-type: application/vnd.elasticsearch+json; compatible-with=8
accept: application/vnd.elasticsearch+json; compatible-with=8
content-length: 3490
traceparent: 00-8cc24eb6df13d4d818db3913085b1233-38dc37abe48e9dc5-00
tracestate: es=s:0
Host: quesma:8080
Connection: keep-alive

{
  "_source": false,
  "fields": [
    "event.dataset",
    "apache2.access.*",
    "apache2.access.remote_ip",
    "apache2.access.user_name",
    "apache2.access.method",
    "apache2.access.url",
    "apache2.access.http_version",
    "apache2.access.response_code",
    "apache2.access.body_sent.bytes",
    "log.level",
    "message",
    "apache2.error.message",
    "apache2.error.level",
    "nginx.access.method",
    "nginx.access.remote_ip",
    "nginx.access.user_name",
    "nginx.access.url",
    "nginx.access.http_version",
    "nginx.access.response_code",
    "nginx.access.body_sent.bytes",
    "nginx.error.message",
    "nginx.error.level",
    "redis.log.message",
    "redis.log.level",
    "system.syslog.message",
    "system.syslog.program",
    "system.auth.message",
    "system.auth.program",
    "system.auth.ssh.event",
    "system.auth.user",
    "system.auth.ssh.ip",
    "system.auth.ssh.dropped_ip",
    "mysql.error.message",
    "ecs.version",
    "mysql.slowlog.query",
    "user.name",
    "source.domain",
    "source.ip",
    "event.duration",
    "mysql.slowlog.user",
    "mysql.slowlog.query_time.sec",
    "mysql.slowlog.host",
    "mysql.slowlog.ip",
    "event.action",
    "event.outcome",
    "auditd.log.*",
    "user.*",
    "process.*",
    "auditd.log.record_type",
    "auditd.log.src",
    "auditd.log.dst",
    "auditd.log.op",
    "auditd.log.exe",
    "auditd.log.gid",
    "auditd.log.uid",
    "auditd.log.tty",
    "auditd.log.pid",
    "auditd.log.ppid",
    "auditd.log.msg",
    "haproxy.http.request.raw_request_line",
    "source.address",
    "source.port",
    "haproxy.frontend_name",
    "haproxy.backend_name",
    "haproxy.server_name",
    "http.response.status_code",
    "haproxy.http.request.time_wait_ms",
    "haproxy.connection_wait_time_ms",
    "haproxy.http.request.time_wait_without_data_ms",
    "haproxy.connections.active",
    "haproxy.connections.frontend",
    "haproxy.connections.backend",
    "haproxy.connections.server",
    "haproxy.connections.retries",
    "haproxy.server_queue",
    "haproxy.backend_queue",
    "haproxy.error_message",
    "haproxy.client.ip",
    "haproxy.client.port",
    "haproxy.http.response.status_code",
    "haproxy.total_waiting_time_ms",
    "haproxy.http.request.time_active_ms",
    "icinga.main.message",
    "icinga.main.facility",
    "icinga.main.severity",
    "icinga.debug.message",
    "icinga.debug.facility",
    "icinga.debug.severity",
    "icinga.startup.message",
    "icinga.startup.facility",
    "icinga.startup.severity",
    "iis.access.method",
    "iis.access.remote_ip",
    "iis.access.user_name",
    "iis.access.url",
    "iis.access.http_version",
    "iis.access.response_code",
    "iis.access.body_sent.bytes",
    "iis.error.url",
    "iis.error.remote_ip",
    "iis.error.method",
    "iis.error.http_version",
    "iis.error.response_code",
    "iis.error.reason_phrase",
    "logstash.log.message",
    "logstash.log.level",
    "logstash.log.module",
    "logstash.slowlog.*",
    "logstash.slowlog.message",
    "logstash.slowlog.level",
    "logstash.slowlog.module",
    "mongodb.log.message",
    "mongodb.log.component",
    "osquery.result.name",
    "osquery.result.action",
    "osquery.result.host_identifier",
    "osquery.result.columns.*",
    "traefik.access.method",
    "traefik.access.remote_ip",
    "traefik.access.frontend_name",
    "traefik.access.backend_url",
    "traefik.access.url",
    "traefik.access.http_version",
    "traefik.access.response_code",
    "traefik.access.body_sent.bytes",
    "url.path",
    "event.module",
    "http.request.method",
    "url.query",
    "http.version",
    "http.response.body.bytes",
    "url.original",
    "error.stack_trace.text",
    "@message",
    "log.original",
    "event.original",
    "log.path",
    "log.file.path",
    "host.name",
    "container.id"
  ],
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "filter": [],
            "must": [],
            "must_not": [],
            "should": []
          }
        },
        {
          "range": {
            "@timestamp": {
              "format": "epoch_millis",
              "gte": 1715839388127,
              "lte": 1715925788127
            }
          }
        }
      ]
    }
  },
  "runtime_mappings": {},
  "size": 201,
  "sort": {
    "@timestamp": "desc",
    "_doc": "desc"
  },
  "track_scores": false,
  "track_total_hits": true
}
