#     DEFAULT QUESMA CONFIG FILE
#
# https://www.notion.so/Quesma-modes-8435eebbb42542dabe6eeb5084299ac6
# ↓ "proxy" (tcp proxy)
#	↓ "proxy-inspect" (tcp proxy with traffic inspection)
#	↓ "dual-write-query-elastic" (dual write with elastics response) (DEFAULT)
#	↓ "dual-write-query-clickhouse" (dual write, query both and compare)
#	↓ "dual-write-query-clickhouse-verify" (dual write, query both and compare, ignore Clickhouse if not the same)
#	↓ "dual-write-query-clickhouse-fallback" (dual write, query both, fallback only when Clickhouse fails)
mode: "dual-write-query-clickhouse"
licenseKey: "cdd749a3-e777-11ee-bcf8-0242ac150004"
port: 8080  # public tcp port to listen for incoming traffic
elasticsearch:
  url: "http://localhost:9200"
  call: false
clickhouse:
  url: "clickhouse://localhost:9000"
ingestStatistics: true
internalTelemetryUrl: "https://api.quesma.com/phone-home"
logging:
  path: "logs"
  level: "info"
  remoteUrl: "https://api.quesma.com/phone-home"
  disableFileLogging: false
indexes:
  - pattern: "kibana_sample_data_ecommerce"
    enabled: true
  - pattern: "kibana_sample_data_flights"
    enabled: true
  - pattern: "kibana_sample_data_logs"
    enabled: true
    aliases:
      timestamp:
        source: "timestamp"
        target: "@timestamp"
  - pattern: "kafka-example-topic"
    enabled: true
  - pattern: "logs-generic-default"
    enabled: true
    fullTextFields: [ "message", "host.name" ]
  - pattern: "device_logs"
    enabled: true
    fullTextFields: [ "message" ]
  - pattern: "phone_home_logs"
    enabled: true
    fullTextFields: [ "message" ]
  - pattern: "windows_logs"
    enabled: true
  - pattern: "phone_home_data"
    enabled: true
    fullTextFields: [ "message" ]


