quesma:
  # https://www.notion.so/Quesma-modes-8435eebbb42542dabe6eeb5084299ac6
  # ↓ "proxy" (tcp proxy)
  #	↓ "proxy-inspect" (tcp proxy with traffic inspection)
  #	↓ "dual-write-query-elastic" (dual write with elastics response) (DEFAULT)
  #	↓ "dual-write-query-clickhouse" (dual write, query both and compare)
  #	↓ "dual-write-query-clickhouse-verify" (dual write, query both and compare, ignore Clickhouse if not the same)
  #	↓ "dual-write-query-clickhouse-fallback" (dual write, query both, fallback only when Clickhouse fails)
  mode: "dual-write-query-clickhouse"
  license_key: "cdd749a3-e777-11ee-bcf8-0242ac150004"
  port: 8080  # public tcp port to listen for incoming traffic
  elasticsearch_url: "http://localhost:9200"
  clickhouse_url: "clickhouse://localhost:9000"
  ingest_statistics: true
  quesma_internal_telemetry_url: "https://api.quesma.com/phone-home"
  logs_path: "logs"
  log_level: "info"
  index:
    kibana_sample_data_ecommerce:
      enabled: true
    kibana_sample_data_flights:
      enabled: true
    kibana_sample_data_logs:
      enabled: true
      alias_fields: timestamp<-@timestamp
    kafka-example-topi*:
      enabled: true
    logs-generic-*:
      enabled: true
      fulltext_fields: message,host.name
    device*:
      enabled: true
      fulltext_fields: message
    phone_home_logs:
      enabled: true
      fulltext_fields: message
    heartbeat-*:
      enabled: false
    traces-apm*:
      enabled: false
    apm-*:
      enabled: false
    logs-elastic_agent-*:
      enabled: false


