name: Build Quesma container image for customers and prospects (private beta repository)

on:
  workflow_dispatch:
    inputs:
      GIT_REF:
        description: 'Commit hash to use for the release (can be a branch name or tag)'
        required: true
      VERSION_TAG:
        description: 'Version tag for the released Docker image'
        required: true

jobs:
  build-quesma-docker-image:
    strategy:
      matrix:
        module: [ "quesma" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.GIT_REF }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

# Probably we don't need this step, to be removed when confirmed
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          cache-dependency-path: ${{ matrix.module }}/go.sum
#          go-version: '1.22'

      - name: Login to GCR (only for build running on `main` branch)
        uses: docker/login-action@v3
        with:
          registry: europe-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT_PRIVATE_KEY }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.module }}/.
          tags: europe-central2-docker.pkg.dev/metal-figure-407109/quesma-private-beta/quesma:${{ github.event.inputs.VERSION_TAG }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max